services:
  - type: web
    name: tradetable
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 60
    envVars:
      - key: FLASK_DEBUG
        value: "false"
      - key: ADMIN_PW
        generateValue: false
        value: "tradetable-admin-2026"
      - key: SECRET_KEY
        generateValue: true
